language: python
python:
  - '2.7'

before_install:
  - sudo add-apt-repository -y "ppa:chris-lea/python-urllib3"
  - sudo apt-get update -q
  - curl -L http://bootstrap.saltstack.org | sudo -E sh -s -- stable 2015.5

install:
  - sudo cp -r salt /srv/
  - sudo cp -r pillar /srv/
  - sudo echo 'mysql.default_file: /etc/mysql/debian.cnf' > /etc/salt/minion
  - sudo echo 'testmachine: OK' > /etc/salt/grains
  - sudo service salt-minion stop
  - sudo salt-call grains.items --local

script:
  - sudo salt-call state.highstate --local --retcode-passthrough
